name: zako3-hq
version: 0.1.0.0
license: MIT
author: "mincomk"
maintainer: "mail@drchi.co.kr"
extra-source-files:
  - README.md

default-extensions:
  - OverloadedStrings
  - LambdaCase
  - DeriveGeneric
  - TypeApplications
  - DataKinds
  - TypeOperators
  - FlexibleContexts
  - DerivingStrategies
  - GeneralizedNewtypeDeriving
  - NamedFieldPuns
  - FlexibleInstances
  - UndecidableInstances
  - ScopedTypeVariables
  - DuplicateRecordFields

dependencies:
  - base

  - containers
  - text
  - bytestring
  - mtl
  - transformers
  - unordered-containers
  - optics

  - directory
  - time

  - mongoDB
  - hedis
  - katip
  - conferer
  - aeson

  - servant
  - servant-server
  - wai-websockets
  - websockets

  - stm
  - async
  - generic-optics
  - resource-pool
  - data-default-class < 0.2
  - data-default < 0.8.0

  - random
  - cryptohash-sha256

library:
  source-dirs: src
  dependencies:
    - base

executables:
  zako3-hq:
    main: Main.hs
    source-dirs: app
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - base

      - zako3-hq

tests:
  zako3-hq-test:
    main: Spec.hs
    source-dirs: test
    build-tools:
      - hspec-discover:hspec-discover
    dependencies:
      - base

      - zako3-hq

      - hspec
      - hspec-discover
      - hspec-wai
